//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The kube-crisp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRDReference) DeepCopyInto(out *CRDReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRDReference.
func (in *CRDReference) DeepCopy() *CRDReference {
	if in == nil {
		return nil
	}
	out := new(CRDReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceProjection) DeepCopyInto(out *CustomResourceProjection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceProjection.
func (in *CustomResourceProjection) DeepCopy() *CustomResourceProjection {
	if in == nil {
		return nil
	}
	out := new(CustomResourceProjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomResourceProjection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceProjectionList) DeepCopyInto(out *CustomResourceProjectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomResourceProjection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceProjectionList.
func (in *CustomResourceProjectionList) DeepCopy() *CustomResourceProjectionList {
	if in == nil {
		return nil
	}
	out := new(CustomResourceProjectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomResourceProjectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceProjectionSpec) DeepCopyInto(out *CustomResourceProjectionSpec) {
	*out = *in
	in.DataSource.DeepCopyInto(&out.DataSource)
	in.Resource.DeepCopyInto(&out.Resource)
	in.Queries.DeepCopyInto(&out.Queries)
	in.Mapping.DeepCopyInto(&out.Mapping)
	if in.CacheTTL != nil {
		in, out := &in.CacheTTL, &out.CacheTTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Watch != nil {
		in, out := &in.Watch, &out.Watch
		*out = new(WatchSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceProjectionSpec.
func (in *CustomResourceProjectionSpec) DeepCopy() *CustomResourceProjectionSpec {
	if in == nil {
		return nil
	}
	out := new(CustomResourceProjectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceProjectionStatus) DeepCopyInto(out *CustomResourceProjectionStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServedPaths != nil {
		in, out := &in.ServedPaths, &out.ServedPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredSchema != nil {
		in, out := &in.RequiredSchema, &out.RequiredSchema
		*out = new(RequiredSchema)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceProjectionStatus.
func (in *CustomResourceProjectionStatus) DeepCopy() *CustomResourceProjectionStatus {
	if in == nil {
		return nil
	}
	out := new(CustomResourceProjectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSource) DeepCopyInto(out *DataSource) {
	*out = *in
	out.SecretRef = in.SecretRef
	if in.ReadSecretRef != nil {
		in, out := &in.ReadSecretRef, &out.ReadSecretRef
		*out = new(SecretReference)
		**out = **in
	}
	if in.MaxOpenConns != nil {
		in, out := &in.MaxOpenConns, &out.MaxOpenConns
		*out = new(int32)
		**out = **in
	}
	if in.MaxIdleConns != nil {
		in, out := &in.MaxIdleConns, &out.MaxIdleConns
		*out = new(int32)
		**out = **in
	}
	if in.ConnMaxLifetime != nil {
		in, out := &in.ConnMaxLifetime, &out.ConnMaxLifetime
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ConnMaxIdleTime != nil {
		in, out := &in.ConnMaxIdleTime, &out.ConnMaxIdleTime
		*out = new(v1.Duration)
		**out = **in
	}
	if in.PreparedStatements != nil {
		in, out := &in.PreparedStatements, &out.PreparedStatements
		*out = new(bool)
		**out = **in
	}
	if in.StatementTimeout != nil {
		in, out := &in.StatementTimeout, &out.StatementTimeout
		*out = new(bool)
		**out = **in
	}
	if in.KeepAliveInterval != nil {
		in, out := &in.KeepAliveInterval, &out.KeepAliveInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SessionVariables != nil {
		in, out := &in.SessionVariables, &out.SessionVariables
		*out = make([]SessionVariable, len(*in))
		copy(*out, *in)
	}
	if in.MaxConcurrentQueries != nil {
		in, out := &in.MaxConcurrentQueries, &out.MaxConcurrentQueries
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSource.
func (in *DataSource) DeepCopy() *DataSource {
	if in == nil {
		return nil
	}
	out := new(DataSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldMapping) DeepCopyInto(out *FieldMapping) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldMapping.
func (in *FieldMapping) DeepCopy() *FieldMapping {
	if in == nil {
		return nil
	}
	out := new(FieldMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mapping) DeepCopyInto(out *Mapping) {
	*out = *in
	if in.NameColumns != nil {
		in, out := &in.NameColumns, &out.NameColumns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]FieldMapping, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mapping.
func (in *Mapping) DeepCopy() *Mapping {
	if in == nil {
		return nil
	}
	out := new(Mapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotifySpec) DeepCopyInto(out *NotifySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotifySpec.
func (in *NotifySpec) DeepCopy() *NotifySpec {
	if in == nil {
		return nil
	}
	out := new(NotifySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectedResource) DeepCopyInto(out *ProjectedResource) {
	*out = *in
	if in.ShortNames != nil {
		in, out := &in.ShortNames, &out.ShortNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = (*in).DeepCopy()
	}
	if in.SchemaFrom != nil {
		in, out := &in.SchemaFrom, &out.SchemaFrom
		*out = new(CRDReference)
		**out = **in
	}
	if in.AdditionalPrinterColumns != nil {
		in, out := &in.AdditionalPrinterColumns, &out.AdditionalPrinterColumns
		*out = make([]apiextensionsv1.CustomResourceColumnDefinition, len(*in))
		copy(*out, *in)
	}
	if in.SelectableFields != nil {
		in, out := &in.SelectableFields, &out.SelectableFields
		*out = make([]SelectableField, len(*in))
		copy(*out, *in)
	}
	if in.Subresources != nil {
		in, out := &in.Subresources, &out.Subresources
		*out = new(ProjectedSubresources)
		(*in).DeepCopyInto(*out)
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]ProjectedVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectedResource.
func (in *ProjectedResource) DeepCopy() *ProjectedResource {
	if in == nil {
		return nil
	}
	out := new(ProjectedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectedScaleSubresource) DeepCopyInto(out *ProjectedScaleSubresource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectedScaleSubresource.
func (in *ProjectedScaleSubresource) DeepCopy() *ProjectedScaleSubresource {
	if in == nil {
		return nil
	}
	out := new(ProjectedScaleSubresource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectedStatusSubresource) DeepCopyInto(out *ProjectedStatusSubresource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectedStatusSubresource.
func (in *ProjectedStatusSubresource) DeepCopy() *ProjectedStatusSubresource {
	if in == nil {
		return nil
	}
	out := new(ProjectedStatusSubresource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectedSubresources) DeepCopyInto(out *ProjectedSubresources) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(ProjectedStatusSubresource)
		**out = **in
	}
	if in.Scale != nil {
		in, out := &in.Scale, &out.Scale
		*out = new(ProjectedScaleSubresource)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectedSubresources.
func (in *ProjectedSubresources) DeepCopy() *ProjectedSubresources {
	if in == nil {
		return nil
	}
	out := new(ProjectedSubresources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectedVersion) DeepCopyInto(out *ProjectedVersion) {
	*out = *in
	if in.Served != nil {
		in, out := &in.Served, &out.Served
		*out = new(bool)
		**out = **in
	}
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = (*in).DeepCopy()
	}
	if in.SchemaFrom != nil {
		in, out := &in.SchemaFrom, &out.SchemaFrom
		*out = new(CRDReference)
		**out = **in
	}
	if in.Mapping != nil {
		in, out := &in.Mapping, &out.Mapping
		*out = new(Mapping)
		(*in).DeepCopyInto(*out)
	}
	if in.AdditionalPrinterColumns != nil {
		in, out := &in.AdditionalPrinterColumns, &out.AdditionalPrinterColumns
		*out = make([]apiextensionsv1.CustomResourceColumnDefinition, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectedVersion.
func (in *ProjectedVersion) DeepCopy() *ProjectedVersion {
	if in == nil {
		return nil
	}
	out := new(ProjectedVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Queries) DeepCopyInto(out *Queries) {
	*out = *in
	in.List.DeepCopyInto(&out.List)
	if in.Get != nil {
		in, out := &in.Get, &out.Get
		*out = new(Query)
		(*in).DeepCopyInto(*out)
	}
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(Query)
		(*in).DeepCopyInto(*out)
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(Query)
		(*in).DeepCopyInto(*out)
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(Query)
		(*in).DeepCopyInto(*out)
	}
	if in.MarkDeleted != nil {
		in, out := &in.MarkDeleted, &out.MarkDeleted
		*out = new(Query)
		(*in).DeepCopyInto(*out)
	}
	if in.DeleteCollection != nil {
		in, out := &in.DeleteCollection, &out.DeleteCollection
		*out = new(Query)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdateStatus != nil {
		in, out := &in.UpdateStatus, &out.UpdateStatus
		*out = new(Query)
		(*in).DeepCopyInto(*out)
	}
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(Query)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Queries.
func (in *Queries) DeepCopy() *Queries {
	if in == nil {
		return nil
	}
	out := new(Queries)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Query) DeepCopyInto(out *Query) {
	*out = *in
	if in.Statements != nil {
		in, out := &in.Statements, &out.Statements
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]QueryParameter, len(*in))
		copy(*out, *in)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxRows != nil {
		in, out := &in.MaxRows, &out.MaxRows
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Query.
func (in *Query) DeepCopy() *Query {
	if in == nil {
		return nil
	}
	out := new(Query)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryParameter) DeepCopyInto(out *QueryParameter) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryParameter.
func (in *QueryParameter) DeepCopy() *QueryParameter {
	if in == nil {
		return nil
	}
	out := new(QueryParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequiredColumn) DeepCopyInto(out *RequiredColumn) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequiredColumn.
func (in *RequiredColumn) DeepCopy() *RequiredColumn {
	if in == nil {
		return nil
	}
	out := new(RequiredColumn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequiredSchema) DeepCopyInto(out *RequiredSchema) {
	*out = *in
	if in.Tables != nil {
		in, out := &in.Tables, &out.Tables
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Columns != nil {
		in, out := &in.Columns, &out.Columns
		*out = make([]RequiredColumn, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequiredSchema.
func (in *RequiredSchema) DeepCopy() *RequiredSchema {
	if in == nil {
		return nil
	}
	out := new(RequiredSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectableField) DeepCopyInto(out *SelectableField) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectableField.
func (in *SelectableField) DeepCopy() *SelectableField {
	if in == nil {
		return nil
	}
	out := new(SelectableField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionVariable) DeepCopyInto(out *SessionVariable) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionVariable.
func (in *SessionVariable) DeepCopy() *SessionVariable {
	if in == nil {
		return nil
	}
	out := new(SessionVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WatchSpec) DeepCopyInto(out *WatchSpec) {
	*out = *in
	if in.HistorySize != nil {
		in, out := &in.HistorySize, &out.HistorySize
		*out = new(int32)
		**out = **in
	}
	if in.PollInterval != nil {
		in, out := &in.PollInterval, &out.PollInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Query != nil {
		in, out := &in.Query, &out.Query
		*out = new(Query)
		(*in).DeepCopyInto(*out)
	}
	if in.FollowerPollInterval != nil {
		in, out := &in.FollowerPollInterval, &out.FollowerPollInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Notify != nil {
		in, out := &in.Notify, &out.Notify
		*out = new(NotifySpec)
		**out = **in
	}
	if in.DeletedQuery != nil {
		in, out := &in.DeletedQuery, &out.DeletedQuery
		*out = new(Query)
		(*in).DeepCopyInto(*out)
	}
	if in.FullResyncInterval != nil {
		in, out := &in.FullResyncInterval, &out.FullResyncInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.BookmarkInterval != nil {
		in, out := &in.BookmarkInterval, &out.BookmarkInterval
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WatchSpec.
func (in *WatchSpec) DeepCopy() *WatchSpec {
	if in == nil {
		return nil
	}
	out := new(WatchSpec)
	in.DeepCopyInto(out)
	return out
}
