package plugin

import (
	"context"
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	rbacv1 "k8s.io/api/rbac/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/sets"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/kubernetes"

	crispclient "github.com/mrueg/kube-crisp/pkg/generated/clientset/versioned"
	"github.com/mrueg/kube-crisp/pkg/rbac"
)

type pruneOptions struct {
	client      clientFlags
	delete      bool
	apiServices bool
}

// NewCommandPrune builds the `prune` subcommand.
func NewCommandPrune(out, errOut io.Writer) *cobra.Command {
	o := &pruneOptions{}

	cmd := &cobra.Command{
		Use:   "prune",
		Short: "Find RBAC left behind by deleted projections",
		Long: "Lists the ClusterRoles generated by `kubectl crisp rbac` whose projected API group\n" +
			"nothing serves any more.\n\n" +
			"Deleting a projection takes its API group away, but nothing takes away the role\n" +
			"that granted it — and an orphaned role is quiet rather than broken, which is why\n" +
			"it needs a command to find it. It grants verbs on a group nothing serves, until\n" +
			"the day somebody projects that group name again and the old grant applies to the\n" +
			"new rows.\n\n" +
			"A group is served when a projection in the cluster declares it, or when an\n" +
			"APIService kube-crisp wrote for it exists. The second is what a projection loaded\n" +
			"from --projection-dir looks like from the cluster: there is no object to find, and\n" +
			"the group is answered for all the same. Its roles are as live as any, and this\n" +
			"command leaves them be. Whether the aggregation layer currently reports that\n" +
			"APIService available does not enter into it, because a restarting server makes\n" +
			"every one of its registrations unavailable for a while, and a prune run in that\n" +
			"window must not read the outage as every file-backed group having gone.\n\n" +
			"The bindings that reference an orphaned role go with it. A ClusterRoleBinding, and\n" +
			"also a RoleBinding in any namespace, since that is how a namespaced projected kind\n" +
			"is granted per tenant — leaving those behind would leave a reference to a role that\n" +
			"no longer exists.\n\n" +
			"`--apiservices` looks for the other thing a projection leaves behind: the\n" +
			"registration that routed its group here. Those are owned by the projection and go\n" +
			"with it, except for a group served from `--projection-dir`, which has no object\n" +
			"whose deletion could collect it — so stopping the server without first removing\n" +
			"the files strands one. A stranded registration is a cluster-scoped object the\n" +
			"aggregation layer goes on dialling, and it degrades `kubectl api-resources` for\n" +
			"the whole cluster rather than only for that group. It also keeps its group counted\n" +
			"as served, so the order that finds everything is `--apiservices --delete` first,\n" +
			"then a plain `--delete` for the roles the removed registrations were holding up.\n\n" +
			"Prints what it would remove. Pass --delete to remove it.",
		Args:         cobra.NoArgs,
		SilenceUsage: true,
		RunE: func(c *cobra.Command, args []string) error {
			return o.run(c.Context(), out, errOut)
		},
	}

	// prune takes no arguments, and saying so is what stops the shell offering
	// filenames in a position that accepts nothing.
	cmd.ValidArgsFunction = cobra.NoFileCompletions

	cmd.Flags().BoolVar(&o.delete, "delete", false,
		"Delete what was found rather than printing it.")
	cmd.Flags().BoolVar(&o.apiServices, "apiservices", false,
		"Look for stranded APIServices instead of orphaned ClusterRoles. One kind of leftover "+
			"per run, so that what --delete would remove is never two things at once.")
	o.client.bind(cmd)

	return cmd
}

func (o *pruneOptions) run(ctx context.Context, out, errOut io.Writer) error {
	crisp, err := o.client.crisp()
	if err != nil {
		return err
	}

	// Both halves read the APIServices: one to find the stranded ones, the
	// other because a registration is the only trace a file-backed projection
	// leaves in the cluster.
	dyn, err := o.client.dynamic()
	if err != nil {
		return err
	}
	if o.apiServices {
		return o.pruneAPIServices(ctx, crisp, dyn, out, errOut)
	}

	kube, err := o.client.kube()
	if err != nil {
		return err
	}
	return o.prune(ctx, crisp, kube, dyn, out, errOut)
}

// prune takes its clients rather than building them, so that what it does with
// them is testable without a cluster — which for a command whose --delete
// removes objects is the half worth testing.
func (o *pruneOptions) prune(
	ctx context.Context,
	crisp crispclient.Interface,
	kube kubernetes.Interface,
	dyn dynamic.Interface,
	out, errOut io.Writer,
) error {
	orphans, held, err := orphanedRoles(ctx, crisp, kube, dyn)
	if err != nil {
		return err
	}

	// Said whether or not anything was found. A role kept because a stranded
	// registration still names its group is indistinguishable, from the
	// outside, from one this command missed — and the way to release it is a
	// different run.
	for _, stranded := range held {
		_, _ = fmt.Fprintf(errOut,
			"%s is unavailable and nothing claims it, and its group counts as served while it exists: "+
				"the server may be restarting, or the registration is stranded. `prune --apiservices` "+
				"tells which, and removing it is what lets the roles for that group be pruned.\n",
			stranded.name)
	}

	if len(orphans) == 0 {
		_, _ = fmt.Fprintln(errOut, "no orphaned roles")
		return nil
	}

	names := sets.New[string]()
	for i := range orphans {
		names.Insert(orphans[i].Name)
	}
	bindings, err := bindingsTo(ctx, kube, names)
	if err != nil {
		return err
	}

	if !o.delete {
		for i := range orphans {
			role := &orphans[i]
			_, _ = fmt.Fprintf(out, "%s\t(%s: no projection declares this group and no registration kube-crisp wrote for it exists)\n",
				role.Name, role.Labels[rbac.GroupLabel])
			for _, binding := range bindings {
				if binding.role == role.Name {
					_, _ = fmt.Fprintf(out, "  %s\t(bound to it)\n", binding)
				}
			}
		}
		_, _ = fmt.Fprintf(errOut, "\n%d orphaned role(s) and %d binding(s). Pass --delete to remove them.\n",
			len(orphans), len(bindings))
		return nil
	}

	// Bindings first. Either order leaves something behind if the second half
	// fails, and this is the half worth keeping: a role with no binding grants
	// nothing and a re-run removes it, where a binding whose roleRef has gone
	// is the dangling reference this exists to clean up.
	for _, binding := range bindings {
		if err := binding.delete(ctx, kube); err != nil {
			return err
		}
		_, _ = fmt.Fprintf(out, "%s deleted\n", binding)
	}

	for i := range orphans {
		role := &orphans[i]
		err := kube.RbacV1().ClusterRoles().Delete(ctx, role.Name, metav1.DeleteOptions{})
		switch {
		case apierrors.IsNotFound(err):
			// Deleted between the list and now. Nothing to report: the role is
			// gone, which is what was asked for.
		case err != nil:
			return fmt.Errorf("deleting %s: %w", role.Name, err)
		default:
			_, _ = fmt.Fprintf(out, "clusterrole.rbac.authorization.k8s.io/%s deleted\n", role.Name)
		}
	}
	return nil
}

// boundReference is one binding that names an orphaned role. A RoleBinding
// carries the namespace it lives in; a ClusterRoleBinding leaves it empty.
type boundReference struct {
	name      string
	namespace string
	role      string
}

func (b boundReference) String() string {
	if b.namespace == "" {
		return "clusterrolebinding.rbac.authorization.k8s.io/" + b.name
	}
	return fmt.Sprintf("rolebinding.rbac.authorization.k8s.io/%s -n %s", b.name, b.namespace)
}

func (b boundReference) delete(ctx context.Context, kube kubernetes.Interface) error {
	var err error
	if b.namespace == "" {
		err = kube.RbacV1().ClusterRoleBindings().Delete(ctx, b.name, metav1.DeleteOptions{})
	} else {
		err = kube.RbacV1().RoleBindings(b.namespace).Delete(ctx, b.name, metav1.DeleteOptions{})
	}
	if err != nil && !apierrors.IsNotFound(err) {
		return fmt.Errorf("deleting %s: %w", b, err)
	}
	return nil
}

// bindingsTo finds every binding whose roleRef names one of the given roles.
//
// Both kinds, because both are how a projected group is granted: a
// ClusterRoleBinding for a cluster-scoped kind, and a RoleBinding referencing
// the same ClusterRole for a namespaced one, which is what scopes a
// tenant-column projection to one tenant.
//
// Matched on the roleRef alone. These bindings carry no label of this
// command's — they are written by whoever decided who may read the projection —
// so what makes one a candidate is that it points at a role that is going away,
// and nothing else.
func bindingsTo(ctx context.Context, kube kubernetes.Interface, roles sets.Set[string]) ([]boundReference, error) {
	refersToOrphan := func(ref rbacv1.RoleRef) bool {
		return ref.Kind == "ClusterRole" && ref.APIGroup == rbacv1.GroupName && roles.Has(ref.Name)
	}

	var out []boundReference

	clusterBindings, err := kube.RbacV1().ClusterRoleBindings().List(ctx, metav1.ListOptions{})
	if err != nil {
		return nil, fmt.Errorf("listing cluster role bindings: %w", err)
	}
	for i := range clusterBindings.Items {
		binding := &clusterBindings.Items[i]
		if refersToOrphan(binding.RoleRef) {
			out = append(out, boundReference{name: binding.Name, role: binding.RoleRef.Name})
		}
	}

	// Every namespace: a projection mapping a tenant column onto
	// metadata.namespace is granted a namespace at a time, so the bindings are
	// spread across as many namespaces as there are tenants.
	roleBindings, err := kube.RbacV1().RoleBindings(metav1.NamespaceAll).List(ctx, metav1.ListOptions{})
	if err != nil {
		return nil, fmt.Errorf("listing role bindings: %w", err)
	}
	for i := range roleBindings.Items {
		binding := &roleBindings.Items[i]
		if refersToOrphan(binding.RoleRef) {
			out = append(out, boundReference{
				name:      binding.Name,
				namespace: binding.Namespace,
				role:      binding.RoleRef.Name,
			})
		}
	}

	sort.Slice(out, func(i, j int) bool {
		if out[i].namespace != out[j].namespace {
			return out[i].namespace < out[j].namespace
		}
		return out[i].name < out[j].name
	})
	return out, nil
}

// orphanedRoles returns the generated roles whose group nothing serves any
// more, and the stranded registrations whose groups are being kept on their
// account, so that the command can say why a role it might have been expected
// to find is not in the list.
//
// Served means a projection in the cluster declares the group, or a
// registration kube-crisp wrote for it exists. The second is not a nicety: a
// projection loaded from --projection-dir has no object in the cluster, and a
// command that only looked for objects would call every role for such a group
// orphaned and, with --delete, cut off every tenant bound to one. The
// APIService is the only trace such a projection leaves, and the same survey
// the --apiservices half runs is what reads it.
//
// Existing is the whole test; whether the aggregation layer reports the
// registration available is not part of it. A rolling restart or an upgrade
// of the server leaves every registration it owns unavailable for a while,
// and a prune that read the verdict would spend that window seeing every
// file-backed group as unserved — the outage above, one restart away. A
// registration that is stranded rather than restarting is the --apiservices
// half's to remove, and the group it held stops counting once it is gone.
//
// What is served is settled first and a failure there is fatal, which is the
// safety property this rests on: an error listing either the projections or
// the registrations would leave groups looking unserved, and generated roles
// looking orphaned. Nothing may be deleted on the strength of a list that did
// not complete — least of all when the list that failed is the one that stands
// in for the projections nobody can list.
func orphanedRoles(
	ctx context.Context,
	crisp crispclient.Interface,
	kube kubernetes.Interface,
	dyn dynamic.Interface,
) ([]rbacv1.ClusterRole, []strandedAPIService, error) {
	survey, err := surveyAPIServices(ctx, crisp, dyn)
	if err != nil {
		return nil, nil, fmt.Errorf("cannot tell which groups are served, so no role is orphaned: %w", err)
	}
	served := survey.served

	// Selected by the label rather than by the name pattern, so a role
	// generated under --name-prefix is found too, and so nothing without the
	// label can ever be considered — a hand-written role that happens to grant
	// a projected group is somebody's, not this command's.
	roles, err := kube.RbacV1().ClusterRoles().List(ctx, metav1.ListOptions{
		LabelSelector: rbac.GroupLabel,
	})
	if err != nil {
		return nil, nil, fmt.Errorf("listing cluster roles: %w", err)
	}

	var orphans []rbacv1.ClusterRole
	granted := sets.New[string]()
	for i := range roles.Items {
		role := roles.Items[i]
		group, labelled := role.Labels[rbac.GroupLabel]
		if !labelled || group == "" {
			// The selector matched, so the label is present; an empty value is
			// a role somebody edited, and guessing at what it meant is not
			// this command's business.
			continue
		}
		granted.Insert(group)
		if !served.Has(group) {
			orphans = append(orphans, role)
		}
	}

	// Only the stranded registrations that are holding a role up are worth
	// naming; one for a group nobody generated a role for keeps nothing
	// from this half, and is --apiservices's alone.
	var held []strandedAPIService
	for _, stranded := range survey.stranded {
		if group, _, _ := strings.Cut(stranded.groupVersion, "/"); granted.Has(group) {
			held = append(held, stranded)
		}
	}

	sort.Slice(orphans, func(i, j int) bool { return orphans[i].Name < orphans[j].Name })
	return orphans, held, nil
}
