package plugin

import (
	"context"
	"fmt"
	"io"
	"sort"

	"github.com/spf13/cobra"
	rbacv1 "k8s.io/api/rbac/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/sets"
	"k8s.io/client-go/kubernetes"

	crispclient "github.com/mrueg/kube-crisp/pkg/generated/clientset/versioned"
	"github.com/mrueg/kube-crisp/pkg/rbac"
)

type pruneOptions struct {
	client clientFlags
	delete bool
}

// NewCommandPrune builds the `prune` subcommand.
func NewCommandPrune(out, errOut io.Writer) *cobra.Command {
	o := &pruneOptions{}

	cmd := &cobra.Command{
		Use:   "prune",
		Short: "Find RBAC left behind by deleted projections",
		Long: "Lists the ClusterRoles generated by `kubectl crisp rbac` whose projected API group\n" +
			"no longer has a projection behind it.\n\n" +
			"Deleting a projection takes its API group away, but nothing takes away the role\n" +
			"that granted it — and an orphaned role is quiet rather than broken, which is why\n" +
			"it needs a command to find it. It grants verbs on a group nothing serves, until\n" +
			"the day somebody projects that group name again and the old grant applies to the\n" +
			"new rows.\n\n" +
			"Prints what it would remove. Pass --delete to remove it.",
		Args:         cobra.NoArgs,
		SilenceUsage: true,
		RunE: func(c *cobra.Command, args []string) error {
			return o.run(c.Context(), out, errOut)
		},
	}

	cmd.Flags().BoolVar(&o.delete, "delete", false,
		"Delete the orphaned roles rather than printing them.")
	o.client.bind(cmd)

	return cmd
}

func (o *pruneOptions) run(ctx context.Context, out, errOut io.Writer) error {
	crisp, err := o.client.crisp()
	if err != nil {
		return err
	}
	kube, err := o.client.kube()
	if err != nil {
		return err
	}

	orphans, err := orphanedRoles(ctx, crisp, kube)
	if err != nil {
		return err
	}
	if len(orphans) == 0 {
		_, _ = fmt.Fprintln(errOut, "no orphaned roles")
		return nil
	}

	for i := range orphans {
		role := &orphans[i]
		group := role.Labels[rbac.GroupLabel]

		if !o.delete {
			_, _ = fmt.Fprintf(out, "%s\t(%s: no projection serves this group)\n", role.Name, group)
			continue
		}

		err := kube.RbacV1().ClusterRoles().Delete(ctx, role.Name, metav1.DeleteOptions{})
		switch {
		case apierrors.IsNotFound(err):
			// Deleted between the list and now. Nothing to report: the role is
			// gone, which is what was asked for.
		case err != nil:
			return fmt.Errorf("deleting %s: %w", role.Name, err)
		default:
			_, _ = fmt.Fprintf(out, "clusterrole.rbac.authorization.k8s.io/%s deleted\n", role.Name)
		}
	}

	if !o.delete {
		_, _ = fmt.Fprintf(errOut, "\n%d orphaned role(s). Pass --delete to remove them.\n", len(orphans))
	}
	return nil
}

// orphanedRoles returns the generated roles whose group no longer has a
// projection.
//
// The projections are listed first and a failure there is fatal, which is the
// safety property this rests on: an error listing them would leave every group
// looking unserved, and every generated role in the cluster looking orphaned.
// Nothing may be deleted on the strength of a list that did not complete.
func orphanedRoles(
	ctx context.Context,
	crisp crispclient.Interface,
	kube kubernetes.Interface,
) ([]rbacv1.ClusterRole, error) {
	projections, err := crisp.CrispV1alpha1().CustomResourceProjections().List(ctx, metav1.ListOptions{})
	if err != nil {
		return nil, fmt.Errorf("listing projections: %w", err)
	}

	served := sets.New[string]()
	for i := range projections.Items {
		served.Insert(projections.Items[i].Spec.Resource.Group)
	}

	// Selected by the label rather than by the name pattern, so a role
	// generated under --name-prefix is found too, and so nothing without the
	// label can ever be considered — a hand-written role that happens to grant
	// a projected group is somebody's, not this command's.
	roles, err := kube.RbacV1().ClusterRoles().List(ctx, metav1.ListOptions{
		LabelSelector: rbac.GroupLabel,
	})
	if err != nil {
		return nil, fmt.Errorf("listing cluster roles: %w", err)
	}

	var orphans []rbacv1.ClusterRole
	for i := range roles.Items {
		role := roles.Items[i]
		group, labelled := role.Labels[rbac.GroupLabel]
		if !labelled || group == "" {
			// The selector matched, so the label is present; an empty value is
			// a role somebody edited, and guessing at what it meant is not
			// this command's business.
			continue
		}
		if !served.Has(group) {
			orphans = append(orphans, role)
		}
	}

	sort.Slice(orphans, func(i, j int) bool { return orphans[i].Name < orphans[j].Name })
	return orphans, nil
}
